sudo: false
language: node_js
node_js:
  - "node"
  - "8"
before_install: 
  - cd server
before_script:
  - npm install
  - npm install coveralls --save-dev
  - npm install mocha-lcov-reporter --save-dev
  - npm install supertest 
script:
  - node app.js &
  - npm test
after_success:
  - npm run coveralls
