sudo: false
language: node_js
node_js:
  - "node"
  - "8"
before_install: 
  - cd server
before_script:
  - npm install
  - npm install supertest 
  - npm install --save-dev coveralls mocha-lcov-reporter
script:
  - node app.js &
  - npm test
after_success:
  - npm run coveralls
