sudo: false
language: node_js
node_js:
  - "node"
  - "8"
before_install: 
  - cd server
before_script:
  - npm install
  - npm install nodemon
  - npm install express
script:
  - node app.js
  - npm test
